#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SCaR_Arcade.Resource", IsApplication=true)]

namespace SCaR_Arcade
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Disk = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int game1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int game2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int game3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gameBase = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int info = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int minus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int plus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Pole = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int btnGameSelect = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int btnLeaderBoard = 2131034120;
			
			// aapt resource value: 0x7f050019
			public const int btnQuit = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int btnReplay = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int btnStart = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int cTimer = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int imgBtnDecrease = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int imgBtnIncrease = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int linLayGameDisplay = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout3 = 2131034129;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout4 = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout5 = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int logo = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int lvGameList = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int relativeLayout1 = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int titletxt = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int tvGameTitle = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int txtDifficulty = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int txtErrorMessage = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int txtGameTitle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int txtSltGame = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int txtVElapsedTime = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int txtVScore = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int txtViewOptNoOfMoves = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Leaderboard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TowersOfHanoi = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
